modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="gooeylibs2"
version="${version}"
displayName="GooeyLibs2"
authors="landonjw"
description='''
Server-side library that allows for easy user interface development.
'''

[[dependencies.gooeylibs2]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="SERVER"

[[dependencies.gooeylibs2]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="SERVER"
